- name: Download sliver-server_linux from GitHub if it's missing or older than a week
  ansible.builtin.get_url:
    url: "https://github.com/BishopFox/sliver/releases/latest/download/sliver-server_linux"
    dest: "{{ c2_framework_download_path }}/"
    mode: '0755'
    force: true
  tags: tested
