# Update this with the hosts in your infrastructure

# Format like so:
# group-name:
#   hosts:
#     name-for-host-here:
#       ansible_host: IP.ADDR.GOES.HERE | server.domain.name
#       ansible_port: SSH-PORT
#       ansible_connection: local  # if just working on localhost, no SSH
#     second-host-here:
# OR
# hostname ansible_host=IP.ADDR.GOES.HERE
# IP.ADDR.GOES.HERE
# IP.ADDR.GOES.HERE ansible_ssh_user=root

# localhost ansible_host=127.0.0.1

attack_hosts:
  hosts:
    localhost:
      ansible_host: localhost
      ansible_connection: local

c2_servers:
  hosts:
    localhost:
      ansible_host: localhost
      ansible_connection: local

redirectors:
  hosts: