- name: Download rustyhogs-scripts from GitHub
  ansible.builtin.get_url:
    url: "{{ rustyhogs_scripts_zip_url }}"
    dest: "{{ other_downloads_and_things }}/rustyhogs/zips/"
    mode: '0755'
    force: true
  tags: tested
