- name: Download linpeas.sh from GitHub
  ansible.builtin.get_url:
    url: "https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh"
    dest: "{{ linux_tool_download_path }}/"
    mode: '0755'
    force: true
  tags: tested
