- name: Install docker.io and related packages
  become: true
  ansible.builtin.package:
    name:
      - docker.io
      - docker-doc
      # This was just pulled out of Debian testing and Kali rolling
      # Commenting it out for now.
      - docker-compose
    state: latest
    tags: tested
