- name: Install peass package
  become: true
  ansible.builtin.package:
    name: peass
    state: latest
  # tags: tested

- name: Check file attributes of the linpeas.sh file
  ansible.builtin.stat:
    path: "{{ linux_tool_download_path }}/linpeas.sh"
  register: linpeas_sh_stat

- name: Donwload latest linpeas.sh script from GitHub
  ansible.builtin.include_tasks: download-linpeas-script.yml
  # `|float` is included in this comparison to typecast these variables as floats for the mathematical comparison with 604800.
  # the 604800 value is the number of seconds in a week
  when: (linpeas_sh_stat.stat.mtime is not defined) or ((ansible_date_time.epoch|float - linpeas_sh_stat.stat.mtime|float) > 604800)

- name: Check file attributes of the winPEAS.bat file
  ansible.builtin.stat:
    path: "{{ windows_tool_download_path }}/winPEAS.bat"
  register: winpeas_bat_stat

- name: Download latest winPEAS.bat from GitHub
  ansible.builtin.include_tasks: download-winpeas-bat.yml
  when: (winpeas_bat_stat.stat.mtime is not defined) or ((ansible_date_time.epoch|float - winpeas_bat_stat.stat.mtime|float) > 604800)

- name: Check file attributes of the winPEASany.exe file
  ansible.builtin.stat:
    path: "{{ windows_tool_download_path }}/winPEASany.exe"
  register: winpeas_exe_stat

- name: Download latest winPEASany.exe from GitHub
  ansible.builtin.include_tasks: download-winpeas-exe.yml
  when: (winpeas_exe_stat.stat.mtime is not defined) or ((ansible_date_time.epoch|float - winpeas_exe_stat.stat.mtime|float) > 604800)
